version: '3.3'
services:
  api:
    container_name: 'wallet-api'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    expose:
      - 3000
    ports:
      - 3000:3000
    depends_on:
      - pg
    command: bash -c 'yarn migration:run && yarn dev'
    restart: on-failure
  pg:
    container_name: database
    image: postgres
    env_file:
      - .env
    expose:
      - 5432
    ports:
      - 5432:5432
