version: '3.3'
services:
  api:
    container_name: 'wallet-api'
    env_file:
      - .env
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api/src:/app/src
    expose:
      - ${PORT}
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - pg
    command: bash -c 'yarn migration:run && yarn dev'
    restart: on-failure
  pg:
    container_name: database
    image: postgres
    env_file:
      - .env
    expose:
      - 5432
    ports:
      - 5432:5432
  client:
    container_name: 'wallet-client'
    build:
      context: ./client
      dockerfile: Dockerfile
    expose:
      - 80
    ports:
      - 80:3000
    stdin_open: true
    tty: true
